name: Build, Test, Deploy

on:
  push:
    branches: [master]
    paths-ignore:
      - CONTRIBUTING.md
      - README.md
      - .gitignore

  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [master]

env:
  AZURE_FUNCTIONAPP_NAME: HockeyPickupComms
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './HockeyPickup.Comms'
  DOTNET_VERSION: '9.0.x'

jobs:
  tag_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: HockeyPickup
        DEFAULT_BUMP: patch

  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore Dependencies
      run: |
        dotnet restore
        dotnet tool restore

    - name: Versions
      run: |
        dotnet --version
        git --version
        az --version

    - name: Build
      run: |
        dotnet build --no-restore

    - name: Build Release Version
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --no-restore --configuration Release --output ./output
        popd

    - name: Deploy to Azure Production
      if: github.ref == 'refs/heads/master'
      uses: Azure/functions-action@v1.5.1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        slot-name: 'Production'
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0EC9C5844A4949EDB5C6B31311E264E0 }}
